[tool.poetry]
name = "IPDATA SCANNER"
version = "0.1.0"
description = "IP Scan With Python IPPDATA"
authors = ["x1BTC <x4btc@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ipdata = "^3.4.3"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
